import {useCallback, useEffect, useMemo, useState} from 'react';
import {Activity, ArrowUpRight, Bot, Check, ChevronRight, CirclePause, CirclePlay, Database, ExternalLink, RefreshCw, ShieldCheck, Wallet, X, Zap} from 'lucide-react';

type RecordData = Record<string, any>;
type Tab = 'feed'|'wallets'|'safety'|'astra'|'portfolio'|'momentum';
const tabs: {id:Tab; label:string; icon:typeof Activity}[] = [
  {id:'feed',label:'Live feed',icon:Activity}, {id:'wallets',label:'Wallet intelligence',icon:Wallet},
  {id:'safety',label:'Safety evidence',icon:ShieldCheck}, {id:'astra',label:'Astra analyst',icon:Bot},
  {id:'portfolio',label:'Paper portfolio',icon:Database},
  {id:'momentum',label:'Momentum experiment',icon:Activity},
];
const short = (s?:string) => s ? `${s.slice(0,8)}…${s.slice(-5)}` : 'Unknown';
const number = (n:any, digits=0) => n === null || n === undefined || !Number.isFinite(Number(n)) ? 'Unknown' : Number(n).toLocaleString(undefined,{maximumFractionDigits:digits});
const money = (n:any) => n === null || n === undefined ? 'Unknown' : new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(n);
const age = (ts?:number) => !ts ? 'Unknown' : Math.max(0,Math.floor(Date.now()/1000-ts)) < 60 ? `${Math.max(0,Math.floor(Date.now()/1000-ts))}s ago` : `${Math.floor(Math.max(0,Date.now()/1000-ts)/60)}m ago`;
const readable = (s:string) => s.replaceAll('_',' ');
function Badge({children, tone='neutral'}:{children:React.ReactNode;tone?:string}) { return <span className={`badge ${tone}`}>{children}</span>; }
function Link({value,kind='address'}:{value?:string;kind?:'address'|'tx'}) { return value ? <a className="address" title={value} href={`https://explorer.mainnet.chain.robinhood.com/${kind}/${value}`} target="_blank" rel="noreferrer">{short(value)}<ExternalLink size={12}/></a> : <span className="muted">Unknown</span>; }
function Empty({children}:{children:React.ReactNode}) { return <div className="empty">{children}</div>; }
function Metric({label,value,note}:{label:string;value:string;note?:string}) { return <div className="metric"><span>{label}</span><strong>{value}</strong>{note && <small>{note}</small>}</div>; }

const armNames:Record<string,string> = {wallet_momentum:'Wallet momentum',wallet_momentum_astra:'Wallet momentum + Astra',simple_momentum:'Simple momentum control'};
function EntryReadiness({experiment,scanner,connected}:{experiment:RecordData;scanner?:RecordData;connected:boolean}) {
  const now=Date.now()/1000;
  const feedReady=connected && !!scanner?.last_success && now-scanner.last_success<45 && scanner.lag_blocks<=22 && scanner.status!=='error';
  const workerReady=!!experiment.last_live && now-experiment.last_live<30 && !experiment.live_error;
  const latest=new Map<string,RecordData>();
  for (const d of experiment.decisions || []) {
    if (d.arm==='simple_momentum' && now-d.ts<=120 && !latest.has(d.token)) latest.set(d.token,d);
  }
  const skipped=[...latest.values()].filter(d=>d.action==='SKIP');
  const counts=new Map<string,number>();
  for (const d of skipped) for (const reason of d.reasons) counts.set(reason,(counts.get(reason)||0)+1);
  const blockers=[...counts].sort((a,b)=>b[1]-a[1]).slice(0,4);
  const qualified=experiment.qualified_wallets || 0;
  return <section className="panel evidence-detail" aria-label="Paper entry status">
    <div className="panel-title"><strong>Paper entry status</strong><Badge tone={feedReady && workerReady?'green':'amber'}>{!connected?'DISCONNECTED':!feedReady?'FEED CATCHING UP':!workerReady?'WORKER DELAYED':'CHECKING CANDIDATES'}</Badge></div>
    {!feedReady && <p>Fresh chain data is required before an entry. {connected?`Scanner lag: ${number(scanner?.lag_blocks)} blocks.`:'The displayed records are saved data; worker activity cannot be confirmed.'}</p>}
    <p><b>Wallet strategies:</b> {qualified<2?`Waiting for qualifying history — ${number(qualified)} qualified wallets and ${number(experiment.sample_counts?.complete || 0)} measured outcomes across all wallets. At least two qualified wallets must buy the same token within 60 seconds.`:`${number(qualified)} wallets qualify. Entry still requires two of them buying the same token within 60 seconds and passing all entry checks.`}</p>
    <p><b>Simple momentum control:</b> Runs without qualified-wallet history. {latest.size?`${skipped.length} of the ${latest.size} latest displayed candidates were skipped (assessments from the last two minutes).`:'No fresh candidate decisions to summarize yet.'}</p>
    {blockers.length>0 && <p className="muted">Recent control blockers: {blockers.map(([reason,count])=>`${readable(reason)} (${count})`).join(' · ')}. Full reasons are in the Momentum experiment tab.</p>}
  </section>;
}
function MomentumExperiment({experiment}:{experiment?:RecordData}) {
  if (!experiment) return <Empty>The momentum experiment has not started.</Empty>;
  const e=experiment, counts=e.sample_counts || {};
  const total=Object.values(counts).reduce<number>((n,v)=>n+Number(v),0);
  const fresh=!!e.last_live && Date.now()/1000-e.last_live<30 && !e.live_error;
  const pct=(n:any)=>n==null?'Insufficient data':`${number(n*100,1)}%`;
  return <>
    <div className="section-heading"><div><h2><Activity size={19}/> Followable wallet momentum</h2><p>Separate paper accounts test delayed follower returns. Rules are frozen; profitability is unproven.</p></div><Badge tone={fresh?'green':'amber'}>{fresh?'EXPERIMENT RUNNING':'WAITING FOR WORKER'}</Badge></div>
    {(e.live_error || e.replay_error) && <div className="alert">{e.live_error || e.replay_error}</div>}
    <section className="panel settings"><span>Per entry <b>$2</b></span><span>Stop <b>8%</b></span><span>Target <b>20%</b></span><span>Timeout <b>15 minutes</b></span><span>Buyers <b>2 within 60 seconds</b></span><span>Live check <b>{age(e.last_live)}</b></span></section>
    <div className="review-grid">{e.accounts.map((a:RecordData)=><section className="panel review" key={a.arm}><div className="panel-title"><strong>{armNames[a.arm]}</strong><Badge>{a.fills} fills</Badge></div><div className="review-body"><h3>{money(a.stressed_equity)} <small>stressed equity</small></h3><p>{money(a.cash)} cash · {money(a.realized_pnl)} realized P&amp;L · {a.positions.length} open positions</p><p className="muted">{a.arm==='simple_momentum'?'Same safety and flow checks, without the wallet ranking requirement.':a.arm==='wallet_momentum_astra'?'Two previously qualified wallets plus a fresh Astra MIRROR approval. Actual queue delay counts.':'Two wallets qualified by delayed follower returns, positive net buying, and passing safety checks.'}</p>{a.positions.map((p:RecordData)=><p key={p.id}><Link value={p.token}/> · {money(p.stressed_value)} · <Badge tone={p.stale?'amber':'green'}>{p.stale?'Exit unpriced':p.quote_status}</Badge></p>)}</div></section>)}</div>
    <p className="panel-foot">Each arm starts with its own $40 simulated account. Unknown or stale exits remain open with zero stressed value; they are not recorded as successful sales. The original paper portfolio remains separate.</p>
    <div className="section-heading"><div><h2>Historical follower replay</h2><p>Archive blocks supply delayed entries and exits every 30 seconds. These training outcomes never create live paper fills.</p>{e.replay?.scheduling && <p>{e.replay.scheduling}</p>}</div><span className="muted">Updated {age(e.last_replay)}</span></div>
    <div className="metrics"><Metric label="Observed wallet/token entries" value={number(total)} note={`${number(counts.queued || 0)} queued · ${number(counts.replaying || 0)} replaying`}/><Metric label="Fully measured outcomes" value={number(counts.complete || 0)}/><Metric label="Entries rejected" value={number(counts.entry_rejected || 0)} note="Execution or timing rules failed"/><Metric label="Unresolved / incomplete" value={number((counts.unresolved || 0)+(counts.incomplete || 0))} note="Excluded from measured performance"/><Metric label="Qualified follower wallets" value={number(e.qualified_wallets)} note={`${number(e.ranked_wallets)} wallets evaluated`}/></div>
    {e.replay?.focus && <section className="panel evidence-detail"><div className="panel-title"><strong>Wallet history in focus</strong><Link value={e.replay.focus.wallet}/></div><p><b>{e.replay.focus.measured} fully measured</b> / {Math.max(e.rules.min_samples,Math.ceil(e.replay.focus.total*e.rules.min_coverage))} needed for the sample and coverage checks · {e.replay.focus.total} known entries · {e.replay.focus.pending} still pending. Return statistics and token diversity must also pass.</p><p className="muted">{e.replay.focus.selection}</p></section>}
    {e.replay && <section className="panel evidence-detail"><div className="panel-title"><span>Archive reconstruction v{e.replay.version}</span><Badge>{number(e.replay.fx_candles)} historical FX candles</Badge></div><p className="muted">{number(e.replay.archive_headers)} archive headers verified · {number(e.replay.superseded_samples)} earlier diagnostics preserved and superseded. Identical pool/time cases share reads.</p><div className="schema-counts">{Object.entries(e.replay.case_counts).map(([status,count])=><span key={status}>{readable(status)} cases <b>{number(count)}</b></span>)}</div>{e.replay.active.map((r:RecordData)=><p key={`${r.pool}-${r.entry_target}`}><Link value={r.token}/> · {r.status==='entry'?'Reconstructing delayed entry':'Sampling exits'}{r.entry_at?` · ${number(r.next_target-r.entry_at)} / 900 seconds`:''}{r.reason?` · ${r.reason} · retry ${r.retries}`:''}</p>)}<p className="muted">Fast wallet decoder: {number(e.live_attribution?.reviewed)} transactions reviewed · {age(e.live_attribution?.updated_at)}{e.live_attribution?.error?` · ${e.live_attribution.error}`:''}. Net flow uses confirmed pool swap logs; buyer identities require receipts and traces.</p></section>}
    <section className="panel events"><div className="panel-title">Measured follower outcomes <span className="muted">Historical training · modeled quotes and costs</span></div>{e.priced_samples?.length ? <div className="table-scroll"><table><thead><tr><th>Token</th><th>Followed wallet</th><th>Hold time</th><th>Net modeled return</th><th>Exit trigger</th></tr></thead><tbody>{e.priced_samples.map((r:RecordData)=><tr key={`${r.wallet}-${r.token}`}><td><Link value={r.token}/></td><td><Link value={r.wallet}/></td><td>{number(r.ended_at-r.entry_at)} seconds</td><td className={r.return_fraction>=0?'positive':'negative'}>{pct(r.return_fraction)}</td><td>{readable(r.reason)}<details><summary>Block and quote evidence</summary><pre>{JSON.stringify(JSON.parse(r.path),null,2)}</pre></details></td></tr>)}</tbody></table></div> : <Empty>Archive replay is reconstructing its first complete entry-and-exit paths. Unknown outcomes are not displayed as losses.</Empty>}</section>
    <section className="panel"><div className="panel-title">Wallet ranking <span className="muted">Returns after modeled costs</span></div><div className="table-scroll"><table><thead><tr><th>Wallet</th><th>Measured / entries</th><th>Coverage</th><th>Measured mean</th><th>Mean with stress</th><th>Stress exits</th><th>Qualification</th></tr></thead><tbody>{e.rankings.map((w:RecordData)=><tr key={w.wallet}><td><Link value={w.wallet}/></td><td>{w.samples} / {w.observed_buys}<small className="cellnote">{w.tokens} different tokens</small></td><td>{pct(w.coverage)}</td><td>{pct(w.measured_mean_return)}</td><td>{pct(w.mean_return)}</td><td>{w.stressed_exits}</td><td><Badge tone={w.qualified?'green':'amber'}>{w.qualified?'Qualified':'Insufficient edge / coverage'}</Badge></td></tr>)}</tbody></table></div>{!e.rankings.length && <Empty>Building the historical cohort. No wallet is prequalified from its own P&amp;L.</Empty>}<p className="panel-foot">Requires at least 10 measured follower outcomes across 5 tokens, 80% coverage, 55% wins, stressed mean return at least 2%, and a positive stressed median. Unknown exits contribute −100% only to stress statistics. Rankings must exist before the triggering buys.</p></section>
    <section className="panel events"><div className="panel-title">Live experiment decisions <span className="muted">Latest assessments</span></div><div className="table-scroll"><table><thead><tr><th>Token / time</th><th>Arm</th><th>Signal</th><th>Decision</th><th>Reasons</th></tr></thead><tbody>{e.decisions.map((d:RecordData)=><tr key={d.id}><td><Link value={d.token}/><small className="cellnote">{age(d.ts)}</small></td><td>{armNames[d.arm]}</td><td>{Object.keys(d.signal.buyers).length} distinct buyers · {d.signal.qualified_wallets.length} qualified<small className="cellnote">{d.signal.attributed_transactions}/{d.signal.observed_transactions} transactions attributed · {number(d.signal.net_buy_eth,6)} {d.signal.flow_source==='canonical_pool_swap_logs'?'pool net ETH':'attributed net ETH'}</small></td><td><Badge tone={d.action==='BUY'?'green':'amber'}>{d.action}</Badge></td><td><details><summary>{d.reasons.length} reasons</summary>{d.reasons.map((r:string)=><p key={r}>{readable(r)}</p>)}</details></td></tr>)}</tbody></table></div>{!e.decisions.length && <Empty>Waiting for a fresh assessment after the experiment start. Old signals will not be traded.</Empty>}</section>
    <section className="panel evidence-detail"><h3>Execution model and limitations</h3><p>{e.limitations}</p><p>Live entries get fresh quotes after decision latency. Pool fees are included; each side adds 1% modeled slippage and $0.005 network cost. A stop uses the next available sell quote, which can be much worse than the stop threshold.</p><p>Wallet independence is approximate: distinct holders and transaction senders, with known creator addresses excluded. Common funding and hidden coordination are not fully covered.</p><details><summary>Frozen rules and recent replay evidence</summary><p>Started {new Date(e.started*1000).toLocaleString()} · rules <code>{e.rules_hash.slice(0,16)}</code></p><pre>{JSON.stringify({rules:e.rules,samples:e.samples},null,2)}</pre></details></section>
  </>;
}

function EvidenceLedger({choice,schema}:{choice?:RecordData;schema?:RecordData}) {
  const quality=choice?.evidence_quality;
  const doc=choice?.evidence_contract;
  const measurements=Object.entries(doc?.measurements || {}) as [string,RecordData][];
  const display=(m:RecordData) => m.value===null ? (m.status==='undefined'?'Undefined':'Unknown') : typeof m.value==='boolean' ? String(m.value) : typeof m.value==='number' ? number(m.value,6) : m.value;
  return <section className="panel evidence-detail schema-panel">
    <div className="panel-title"><span><Database size={16}/> Evidence ledger</span><Badge tone={quality?.valid?'green':'amber'}>{quality ? quality.valid?'Schema valid':'Validation blocked':'Awaiting assessment'}</Badge></div>
    {schema && <><div className="schema-counts"><span><b>{number(schema.counts.blocks)}</b> observed blocks</span><span><b>{number(schema.counts.transactions)}</b> transactions</span><span><b>{number(schema.receipts_available)}</b> with receipts</span><span><b>{number(schema.counts.balances)}</b> verified balances</span><span><b>{number(schema.counts.measurements)}</b> measurements</span></div><p className="muted">{schema.coverage}</p>
    <div className="schema-counts">{Object.entries(schema.refresh_counts || {}).map(([status,count])=><span key={status}>{readable(status)} refreshes <b>{number(count)}</b></span>)}</div>
    {schema.sync?.map((s:RecordData)=><p key={s.source} className={s.error?'negative':'muted'}>{readable(s.source)} backfill: {number(s.pending)} records pending{s.error?` · ${s.error}`:''}</p>)}</>}
    {doc && <><p className="muted">Assessment {age(doc.assessed_at)} · schema v{doc.schema_version} · {doc.origin==='legacy_adapter'?'Historical record adapted for display':'Collected with field provenance'}. Freshness is checked now; saved scores describe the assessment time.</p>
    <div className="schema-findings">{quality?.findings?.map((f:RecordData,i:number)=><div key={i}><Badge tone={f.severity==='blocker'?'amber':'neutral'}>{readable(f.code)}</Badge><p>{f.detail}</p><small>{f.follow_up==='none'?'No automatic collector action':`${readable(f.follow_up)} · bounded refresh`}</small></div>)}</div>
    <details><summary>Measurement values and sources · {measurements.length} fields</summary><div className="table-scroll"><table><thead><tr><th>Measurement</th><th>Value / unit</th><th>Status</th><th>Observation</th><th>Source / block</th></tr></thead><tbody>{measurements.map(([key,m])=><tr key={key}><td>{key}<small className="cellnote">{m.scope}</small></td><td>{display(m)}<small className="cellnote">{m.unit}</small></td><td><Badge tone={m.status==='measured'?'green':'amber'}>{m.status}</Badge><small className="cellnote">{m.reason && readable(m.reason)}</small></td><td>{age(m.observed_at)}<small className="cellnote">{quality?.freshness?.[key] || 'Unknown'}</small></td><td>{m.source || 'Unresolved source'}<small className="cellnote">{m.block_number===null?'Block not supplied':m.block_hash?<a href={`https://explorer.mainnet.chain.robinhood.com/block/${m.block_hash}`} target="_blank" rel="noreferrer">Block {number(m.block_number)}</a>:`Block ${number(m.block_number)} · hash unknown`}</small></td></tr>)}</tbody></table></div></details></>}
    {schema?.refresh_recent?.length>0 && <details><summary>Recent data refresh attempts</summary><div className="table-scroll"><table><thead><tr><th>Token</th><th>Request</th><th>Result</th><th>Attempts</th></tr></thead><tbody>{schema?.refresh_recent.map((r:RecordData)=><tr key={`${r.token}-${r.action}`}><td><Link value={r.token}/></td><td>{readable(r.action)}<small className="cellnote">Requested by {r.requested_by}</small></td><td>{r.status}<small className="cellnote">{r.detail}</small></td><td>{r.attempts} / 3</td></tr>)}</tbody></table></div></details>}
  </section>;
}

export default function App() {
  const [data,setData] = useState<RecordData|null>(null);
  const [error,setError] = useState('');
  const [tab,setTab] = useState<Tab>(()=>new URLSearchParams(window.location.search).get('view')==='momentum'?'momentum':'feed');
  const [selected,setSelected] = useState<string|null>(null);
  const [search,setSearch] = useState('');
  const [busy,setBusy] = useState(false);
  const [notice,setNotice] = useState('');
  const refresh = useCallback(async () => {
    try {
      const res = await fetch('/api/state',{cache:'no-store',signal:AbortSignal.timeout(20000)});
      const next = await res.json();
      if (!res.ok) throw new Error(next.error || 'Scanner unavailable');
      setData(next); setError('');
      return next;
    } catch(e) { setError(e instanceof TypeError ? 'Cannot connect to the local terminal. Reconnecting automatically.' : e instanceof Error ? e.message : 'Scanner unavailable'); return null; }
  },[]);
  useEffect(() => {
    let active = true; let timer:ReturnType<typeof setTimeout>;
    const poll = async () => { await refresh(); if(active) timer=setTimeout(poll,5000); };
    void poll(); return () => {active=false; clearTimeout(timer);};
  },[refresh]);
  useEffect(() => {
    const context = (document as Document & {modelContext?:any}).modelContext;
    if (!context?.registerTool) return;
    const lifecycle = new AbortController();
    void Promise.resolve(context.registerTool({
      name:'read_paper_terminal', title:'Read paper terminal',
      description:'Refresh the same live scanner, Astra queue, and paper portfolio shown in the terminal.',
      inputSchema:{type:'object',properties:{},additionalProperties:false},
      annotations:{readOnlyHint:true,untrustedContentHint:true},
      async execute(input:any) {
        if (!input || typeof input!=='object' || Object.keys(input).length) throw new Error('No arguments accepted');
        const state=await refresh(); if(!state) throw new Error('Scanner unavailable');
        return {scanner:state.scanner,counts:state.counts,paper:state.paper,astra:state.ai.astra_live?.counts};
      },
    },{signal:lifecycle.signal})).catch(()=>{});
    return () => lifecycle.abort();
  },[refresh]);
  const command = async (action:string, token?:string) => {
    setBusy(true);setNotice('');
    try {
      const res=await fetch('/api/astra',{method:'POST',headers:{'Content-Type':'application/json','X-Cointrade-Request':'terminal'},body:JSON.stringify({action,token}),signal:AbortSignal.timeout(20000)});
      const result=await res.json(); if(!res.ok) throw new Error(result.error || 'Request failed');
      setNotice(action==='review' ? `Review #${result.id}: ${result.status}.` : action==='pause' ? 'Astra paused. Astra-gated entries paused; mechanical experiment arms and exits remain active.' : 'Astra resumed.');
      await refresh();
    } catch(e) {setNotice(e instanceof Error ? e.message : 'Request failed');}
    finally {setBusy(false);}
  };
  const decisions:RecordData[] = useMemo(() => (data?.decisions || []).filter((d:RecordData,i:number,all:RecordData[])=>all.findIndex(x=>x.token===d.token)===i),[data]);
  const filtered=decisions.filter(d=>`${d.token} ${d.evidence?.symbol||''}`.toLowerCase().includes(search.toLowerCase()));
  const choice=decisions.find(d=>d.token===selected) || filtered[0];
  const astra=data?.ai?.astra_live;
  const reviews:RecordData[]=astra?.recent || [];
  const reviewFor=(token:string)=>reviews.filter(r=>r.token===token).sort((a,b)=>b.id-a.id)[0];
  const scanner=data?.scanner;
  const fresh=!!scanner?.last_success && Date.now()/1000-scanner.last_success<45 && !error;
  const live=fresh && scanner?.lag_blocks<=22 && scanner?.status!=='error';
  const paper=data?.paper;
  const choose=(d:RecordData)=>setSelected(d.token);

  return <div className="terminal">
    <div className="connectionbar"><div><span className={`dot ${live?'on':''}`}/><strong>{live?'LIVE CHAIN DATA':fresh?'CATCHING UP':'FEED DELAYED'}</strong><span>Robinhood Chain · 4663</span><span>{scanner?.provider || 'Connecting'}</span></div><div><span>Block <b>{number(scanner?.cursor)}</b></span><span>Lag {number(scanner?.lag_blocks)} blocks</span><button className="link-button" onClick={()=>void refresh()}><RefreshCw size={13}/> Sync</button></div></div>
    <header className="header"><div className="brand"><div className="brandmark"><Zap size={23}/></div><div><h1>Meme Sniper <span>// Intelligence Terminal</span></h1><p>Live on-chain evidence. Astra High. Paper execution.</p></div></div><Badge tone="green">PAPER TRADING · NO REAL FUNDS</Badge></header>
    <nav aria-label="Terminal views">{tabs.map(t=><button key={t.id} onClick={()=>setTab(t.id)} className={tab===t.id?'active':''}><t.icon size={17}/>{t.label}{t.id==='astra' && (astra?.counts?.running||0)>0 && <span className="dot on"/>}</button>)}</nav>
    <main>
      {error && <div role="alert" className="alert">{error} Last successful data remains visible with its original timestamps.</div>}
      {scanner?.error && <div role="alert" className="alert">Scanner: {scanner.error}</div>}
      {scanner?.enrichment_error && <div className="alert">Enrichment: {scanner.enrichment_error}</div>}
      {notice && <div role="status" className="notice">{notice}<button aria-label="Dismiss notification" onClick={()=>setNotice('')}><X size={16}/></button></div>}
      <section className="metrics"><Metric label="Tokens observed" value={number(data?.counts?.tokens)} note="Since the indexed start block"/><Metric label="Pools indexed" value={number(data?.counts?.pools)} note="Uniswap V2 / V3 / V4"/><Metric label="Wallets observed" value={number(data?.counts?.wallets)} note={`${number(data?.counts?.qualified_wallets)} qualified for mirroring`}/><Metric label="Paper equity" value={paper?money(paper.equity):'Connecting'} note={paper?`${money(paper.cash)} cash · ${number(paper.fills)} fills`:'Loading saved account'}/><Metric label="Astra reviews" value={number(astra?.counts?.complete ?? (data?0:undefined))} note={astra?`${astra.status} · ${astra.counts?.queued||0} queued`:'Connecting to subscription worker'}/></section>
      {!data ? <Empty>Connecting to the live scanner and saved paper account…</Empty> : <>
      {data.momentum && <EntryReadiness experiment={data.momentum} scanner={scanner} connected={!error}/>}
      {tab==='momentum' && <MomentumExperiment experiment={data.momentum}/>}
      {tab==='feed' && <>
        <div className="section-heading"><div><h2><Activity size={18}/> Launch intelligence</h2><p>Latest assessments in this feed. Evidence scores are heuristics; risk rules and Astra both gate entry.</p></div><input aria-label="Search token symbol or address" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search symbol or address"/></div>
        <div className="feed-layout"><section className="panel"><div className="panel-title"><span>Candidate signals</span><Badge>{filtered.length} tokens</Badge></div><div className="table-scroll"><table><thead><tr><th>Token / observed</th><th>Evidence</th><th>Liquidity</th><th>Risk decision</th><th>Astra</th></tr></thead><tbody>{filtered.map(d=><tr key={d.token} className={choice?.token===d.token?'selected':''}><td><button className="token-button" onClick={()=>choose(d)}><strong>{d.evidence?.symbol || short(d.token)}</strong><small>{short(d.token)} · {age(d.ts)}</small></button></td><td><div className="score">{number(d.score,1)}<small>/100</small></div><div className="scorebar"><i style={{width:`${d.score}%`}}/></div></td><td>{money(d.evidence?.liquidity)}</td><td><Badge tone={d.action==='SKIP'?'amber':'green'}>{d.action}</Badge><small className="cellnote">{d.reasons.length} risk blockers</small></td><td><Badge tone={reviewFor(d.token)?.action==='SKIP'?'amber':'neutral'}>{reviewFor(d.token)?.action || reviewFor(d.token)?.status || (d.astra_gate?.[0]?readable(d.astra_gate[0]).replace('astra review ',''):'Not reviewed')}</Badge></td></tr>)}</tbody></table></div>{!filtered.length && <Empty>No assessments match. New candidates appear after scanner enrichment.</Empty>}</section>
        <section className="panel inspector"><div className="panel-title">Selected launch <ChevronRight size={16}/></div>{choice ? <><div className="inspect-head"><h3>{choice.evidence?.symbol || short(choice.token)}</h3><Link value={choice.token}/></div><dl className="facts"><dt>Observed price</dt><dd>{choice.evidence?.price==null?'Unknown':`$${number(choice.evidence.price,10)}`}</dd><dt>Published source</dt><dd>{choice.evidence?.source_verification?.status || 'Unavailable'}</dd><dt>Buy / sell simulation</dt><dd>{choice.evidence?.trade_simulation?.status || 'Unavailable'}</dd><dt>Verified recent buyers</dt><dd>{number(choice.evidence?.distinct_buyers)}</dd><dt>Assessment</dt><dd>{age(choice.ts)}</dd></dl><h4>Entry blockers</h4><ul className="reasons">{[...choice.reasons,...(choice.astra_gate || [])].map((r:string,i:number)=><li key={i}>{readable(r)}</li>)}</ul><button className="primary full" disabled={busy || astra?.status!=='running'} onClick={()=>void command('review',choice.token)}><Bot size={16}/> Review evidence with Astra</button><button className="secondary full" onClick={()=>setTab('safety')}>Inspect safety evidence <ArrowUpRight size={15}/></button></> : <Empty>Select a candidate to inspect its evidence.</Empty>}</section></div>
        <section className="panel events"><div className="panel-title"><span>On-chain activity</span><span className="muted">Confirmed logs · {age(scanner?.last_success)}</span></div><div className="table-scroll"><table><thead><tr><th>Event</th><th>Block</th><th>Token / contract</th><th>Wallet attribution</th><th>Transaction</th></tr></thead><tbody>{data.activity.slice(0,20).map((e:RecordData)=><tr key={e.id}><td><Badge tone={e.kind==='swap'?'green':'neutral'}>{e.kind}{e.side?` · ${e.side}`:''}</Badge></td><td className="mono">{number(e.block)}</td><td><Link value={e.token || e.address}/></td><td>{e.attributed && e.wallet ? <Link value={e.wallet}/> : <span className="muted">Unresolved</span>}</td><td><Link value={e.tx} kind="tx"/></td></tr>)}</tbody></table></div></section>
      </>}
      {tab==='astra' && <>
        <div className="section-heading"><div><h2><Bot size={20}/> Astra analyst</h2><p>One subscription review per detected token. Rechecks use the latest available evidence.</p></div><button className="secondary" disabled={busy || !astra} onClick={()=>void command(astra?.status==='running'?'pause':'resume')}>{astra?.status==='running'?<CirclePause size={17}/>:<CirclePlay size={17}/>} {astra?.status==='running'?'Pause reviews & Astra entries':'Resume reviews & Astra entries'}</button></div>
        <section className="panel model-card"><div className="astra-icon"><Bot size={34}/></div><div><h3>GPT-6 Astra <Badge tone="green">HIGH REASONING</Badge></h3><p className="mono">{astra?.model || 'Not configured'}</p><p>{astra?.billing || 'Worker unavailable'}. Deterministic risk rules remain final.</p></div><div className="model-status"><Badge tone={astra?.status==='running'?'green':'amber'}>{astra?.status || 'Offline'}</Badge><small>{astra?.counts?.running||0} reviewing · {astra?.counts?.queued||0} queued · {astra?.counts?.failed||0} failed</small></div></section>
        {astra?.error && <div className="alert">{astra.error}</div>}
        <div className="review-grid">{reviews.map(r=><article className="panel review" key={r.id}><div className="panel-title"><Link value={r.token}/><Badge tone={r.action==='SKIP'?'amber':r.action?'green':'neutral'}>{r.action || r.status}</Badge></div><div className="review-body"><small>Review #{r.id} · {r.finished_at?age(r.finished_at):r.started_at?'Reviewing now':'Waiting in queue'}</small>{r.evidence && <small className="cellnote">{r.evidence.policy_version===2?'Launch policy v2':'Historical review · earlier policy packet'}</small>}{r.response ? <><p>{r.response.rationale}</p>{[['Known failures',r.response.known_failures],['Missing evidence',r.response.missing_evidence],['Data quality',r.response.data_quality_findings]].map(([title,items]:any)=>(items?.length>0 && <div key={title}><h4>{title}</h4><ul>{items.map((x:string,i:number)=><li key={i}>{x}</li>)}</ul></div>))}{r.response.findings?.length>0 && <details><summary>Structured findings · {r.response.findings.length}</summary>{r.response.findings.map((f:RecordData,i:number)=><p key={i}><b>{readable(f.code)}</b> · {f.detail}<small className="cellnote">{f.evidence_ids.join(', ')} · {readable(f.follow_up)}</small></p>)}</details>}<details><summary>Review provenance</summary><p>Requested model: {r.model} · reasoning: high · ChatGPT subscription</p><p>Evidence assessment: {r.evidence?.ts ? new Date(r.evidence.ts*1000).toLocaleString():'Unassessed token'}</p><p>Input tokens: {number(r.usage?.input_tokens)} · output tokens: {number(r.usage?.output_tokens)}</p><pre>{JSON.stringify(r.evidence,null,2)}</pre></details></> : <p>{r.error || (r.status==='running'?'Astra is analyzing saved on-chain evidence.':'Awaiting the serial subscription worker.')}</p>}</div></article>)}</div>
        {!reviews.length && <Empty>No live reviews yet. Detected tokens will enter the queue automatically.</Empty>}
        <details className="panel previous"><summary>Previous subscription experiment · {data.ai.subscription_experiment?.completed || 0} completed reviews</summary><p>Historical comparison results remain available in the <a href="http://127.0.0.1:8765" target="_blank" rel="noreferrer">original dashboard</a>. They do not authorize current paper entries.</p></details>
      </>}
      {tab==='safety' && <>
        <div className="section-heading"><div><h2><ShieldCheck size={19}/> Safety evidence</h2><p>Unknown values remain unknown. A high evidence score cannot override a failed risk check.</p></div><select aria-label="Select token for safety evidence" value={choice?.token || ''} onChange={e=>setSelected(e.target.value)}>{decisions.map(d=><option value={d.token} key={d.token}>{d.evidence?.symbol || short(d.token)} · {short(d.token)}</option>)}</select></div>
        <EvidenceLedger choice={choice} schema={data.quality.schema}/>{choice ? <><section className="panel safety-summary"><div><h3>{choice.evidence?.symbol || short(choice.token)}</h3><Link value={choice.token}/></div><Badge tone="amber">{choice.action} · {choice.reasons.length} blockers</Badge><strong className="big-score">{number(choice.score,1)}<small>/100 evidence</small></strong></section><div className="safety-grid">{(choice.score_details?.components || []).map((c:RecordData)=><section className="panel evidence-card" key={c.name}><div><h3>{c.name}</h3><Badge tone={c.status==='met'?'green':c.status==='unknown'?'amber':'neutral'}>{readable(c.status)}</Badge></div><strong>{number(c.points,1)} <small>/ {c.maximum}</small></strong><p>{c.detail}</p></section>)}</div><section className="panel evidence-detail"><h3>Execution and data gaps</h3><ul className="reasons">{[...choice.reasons,...(choice.astra_gate||[])].map((r:string,i:number)=><li key={i}>{readable(r)}</li>)}</ul><p className="muted">Raw holder concentration includes pool and custody addresses. Source verification alone does not prove that owner permissions are safe.</p><button className="primary" disabled={busy || astra?.status!=='running'} onClick={()=>void command('review',choice.token)}><Bot size={16}/> Ask Astra to review</button><details><summary>Full saved evidence · {age(choice.ts)}</summary><pre>{JSON.stringify(choice.evidence,null,2)}</pre></details></section></> : <Empty>Waiting for an assessed token.</Empty>}
      </>}
      {tab==='wallets' && <>
        <div className="section-heading"><div><h2><Wallet size={19}/> Wallet intelligence</h2><p>Returns require matched transactions and known cost basis. Observed activity alone does not qualify a wallet.</p></div><Badge>{number(data.counts.qualified_wallets)} qualified</Badge></div>
        <section className="panel"><div className="panel-title">Verified historical audits <span className="muted">Bounded window · ETH accounting</span></div><div className="table-scroll"><table><thead><tr><th>Wallet</th><th>Matched sales</th><th>Known realized P&L</th><th>Reconciled tokens</th><th>Explorer receipts</th><th>Mirroring</th></tr></thead><tbody>{data.wallet_history.audits.map((a:RecordData,i:number)=><tr key={`${a.wallet}-${i}`}><td><Link value={a.wallet}/><small className="cellnote">{new Date(a.coverage.start_time*1000).toLocaleDateString()} – {new Date(a.coverage.end_time*1000).toLocaleDateString()}</small></td><td>{number(a.matched_sales)}<small className="cellnote">{a.unknown_basis_or_unreconciled_sales} excluded sales</small></td><td className={Number(a.realized_pnl_weth)>=0?'positive':'negative'}>{number(a.realized_pnl_weth,8)} ETH</td><td>{a.tokens_reconciled} / {a.tokens}</td><td>{number(a.explorer_crosscheck?.receipt_matches)} matched</td><td><Badge tone={a.mirror_eligible?'green':'amber'}>{a.mirror_eligible?'Eligible':'Not qualified'}</Badge></td></tr>)}</tbody></table></div>{!data.wallet_history.audits.length && <Empty>No completed wallet history audits.</Empty>}<p className="panel-foot">Historical audit P&L covers known-basis matched sales in the stated window. Opening inventory, unresolved tokens, unrealized holdings, and native-only transactions are not complete wallet performance.</p></section>
        <section className="panel events"><div className="panel-title">Observed wallet profiles <span className="muted">Attribution backlog: {number(data.quality.wallet_transactions_pending)} transactions</span></div><div className="table-scroll"><table><thead><tr><th>Wallet</th><th>Closed lots</th><th>Wins / losses</th><th>Matched P&L</th><th>Unresolved records</th><th>Eligibility</th></tr></thead><tbody>{data.wallets.map((w:RecordData)=><tr key={w.wallet}><td><Link value={w.wallet}/></td><td>{number(w.closed_lots)}</td><td>{w.closed_lots?`${w.wins} / ${w.losses}`:'Insufficient history'}</td><td>{w.closed_lots?`${number(w.realized_pnl_weth,8)} ETH`:'Unknown'}</td><td>{number(w.unknown_basis_or_attribution)}</td><td><Badge tone={w.mirror_eligible?'green':'neutral'}>{w.mirror_eligible?'Eligible':'Not qualified'}</Badge></td></tr>)}</tbody></table></div></section>
      </>}
      {tab==='portfolio' && <>
        <div className="section-heading"><div><h2><Database size={19}/> Paper portfolio</h2><p>Persisted simulated fills use observed on-chain quotes, slippage, and fees. No transactions are broadcast.</p></div><Badge tone={paper.halted?'amber':'green'}>{paper.halted?'EQUITY HALT':'PAPER ENGINE ACTIVE'}</Badge></div>
        <div className="metrics portfolio-metrics"><Metric label="Cash" value={money(paper.cash)}/><Metric label="Equity" value={money(paper.equity)}/><Metric label="Realized P&L" value={money(paper.realized_pnl)}/><Metric label="Trading fees" value={money(paper.fees)}/></div>
        <section className="panel settings"><span>Per entry <b>{money(paper.settings?.position_size)}</b></span><span>Max positions <b>{paper.settings?.max_positions}</b></span><span>Stop loss <b>{number(paper.settings?.stop_loss*100)}%</b></span><span>Take profit <b>{number(paper.settings?.take_profit*100)}%</b></span><span>Slippage <b>{paper.settings?.slippage_bps} bps</b></span><span>Astra + risk approval required <Check size={15}/></span></section>
        <section className="panel events"><div className="panel-title">Open positions <Badge>{paper.positions.length}</Badge></div>{paper.positions.length ? <div className="table-scroll"><table><thead><tr><th>Token</th><th>Cost</th><th>Marked value</th><th>Unrealized P&L</th><th>Quote age</th></tr></thead><tbody>{paper.positions.map((p:RecordData)=><tr key={p.token}><td><strong>{p.symbol}</strong><Link value={p.token}/></td><td>{money(p.cost)}</td><td>{money(p.mark*p.quantity)}</td><td>{money(p.unrealized_pnl)}</td><td><Badge tone={p.stale?'amber':'green'}>{p.stale?'Stale · ':''}{age(p.marked_at)}</Badge></td></tr>)}</tbody></table></div> : <Empty><ShieldCheck size={26}/><strong>No paper positions opened</strong><span>Entries wait for fresh quotes, passing risk checks, and Astra approval. A SKIP creates no simulated profit or fill.</span></Empty>}<p className="panel-foot">{paper.valuation}</p></section>
        <section className="panel events"><div className="panel-title">Paper fill ledger <span className="muted">{number(paper.fills)} total fills</span></div>{data.trades.length ? <div className="table-scroll"><table><thead><tr><th>Fill / time</th><th>Token</th><th>Side</th><th>Quantity</th><th>Price</th><th>Fees</th><th>Realized P&L</th></tr></thead><tbody>{data.trades.map((t:RecordData)=><tr key={t.id}><td>Paper #{t.id}<small className="cellnote">{new Date(t.ts*1000).toLocaleString()}</small></td><td><Link value={t.token}/></td><td><Badge>{t.side}</Badge></td><td>{number(t.quantity,6)}</td><td>${number(t.price,10)}</td><td>{money(t.fee)}</td><td>{t.side==='sell'?money(t.pnl):'—'}</td></tr>)}</tbody></table></div> : <Empty>No paper fills yet.</Empty>}</section>
      </>}
      </>}
    </main><footer><span className={`dot ${live?'on':''}`}/><span>{live?'Scanner connected':'Scanner delayed'} · {age(scanner?.last_success)}</span><span>Astra High / subscription</span><span>Live data · simulated orders</span><a href="http://127.0.0.1:8765" target="_blank" rel="noreferrer">Detailed scanner dashboard <ArrowUpRight size={12}/></a></footer>
  </div>;
}
