#!/bin/sh
# Runit restarts this paper-only scanner after exit and starts it after boot.
exec chpst -u jeremy:jeremy /usr/bin/env -i \
  HOME=/home/jeremy USER=jeremy LOGNAME=jeremy LANG=C.UTF-8 \
  PATH=/usr/local/bin:/usr/bin:/bin \
  /bin/bash -c 'exec /srv/git/cointrade/scripts/start-dashboard.sh >> /srv/git/cointrade/data/gui.log 2>&1'
